author: dumptruckman
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.dumptruckman.minecraft.gmtools.GMToolsPlugin
name: GMTools
startup: postworld
version: b${build.number}

depend: [WorldEdit]

commands:
  gm:
    description: Base GMTools command.
    usage: |
           /<command>
  text:
    description: Allows GM to send text without a name to the server.
    usage: |
           /<command> [-r:radius|-g] <text>
  gmtext:
    description: Allows GM to send text without a name to the server.
    usage: |
           /<command> [-r:radius|-g] <text>
  fireball:
    description: Allows GM to shoot a fireball at their crosshair.
    alias: fb
    usage: |
           /<command>
  explode:
    description: Allows GM to explode while moving.
    alias: expl
    usage: |
           /<command>
  suicide:
    description: Murders yourself.
    usage: |
           /<command>